//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSemana.ServicesSemana {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesSemana.ws_BusquedasSoap")]
    public interface ws_BusquedasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_MultimediasByParameter", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        ServiceSemana.ServicesSemana.Multimedia[] lst_MultimediasByParameter(int pageNumber, int pageSize, string filterFind, int idSeccion, int idTipoMultimedia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_GaleriaFindParameterPageIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        ServiceSemana.ServicesSemana.GaleriaFotografica[] lst_GaleriaFindParameterPageIndex(int pageNumber, int pageSize, string filterFind, int idSeccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_GaleriaFindPhotos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        ServiceSemana.ServicesSemana.Fotos_Galeria[] lst_GaleriaFindPhotos(int idGaleria);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_ArticuloFindParameterPageIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        ServiceSemana.ServicesSemana.Articulos[] lst_ArticuloFindParameterPageIndex(int pageNumber, int pageSize, string filterFind, int idSeccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_ArticuloFindAuthorPageIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        ServiceSemana.ServicesSemana.Articulos[] lst_ArticuloFindAuthorPageIndex(int pageNumber, int pageSize, int idAuthor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_CaricaturasFindParameterPageIndex", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        ServiceSemana.ServicesSemana.Articulos[] lst_CaricaturasFindParameterPageIndex(int pageNumber, int pageSize, int idSeccion, int idEdicion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lst_NotificacionUltimosCreados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(GeneralProcess))]
        string lst_NotificacionUltimosCreados();
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Multimedia : GeneralProcess {
        
        private long idMultimediaField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private string fechaCreacionField;
        
        private long usuarios_IdUsuarioField;
        
        private string fechaUltimaModificacionField;
        
        private long seccionesMultimedia_IdSeccionField;
        
        private long tiposMultimedia_IdTipoField;
        
        private long tiposContenidoMultimedia_IdTipoField;
        
        private long publicarSitioWebField;
        
        private string fechaPublicacionField;
        
        private string fechaArchivoField;
        
        private string fuenteResAltaField;
        
        private string fuenteResMediaField;
        
        private string fuenteResBajaField;
        
        private string fuenteResField;
        
        private string resolucionField;
        
        private string formatoDescargaField;
        
        private long estadosPublicacion_IdEstadoField;
        
        private long anchoField;
        
        private long altoField;
        
        private string classidField;
        
        private string codebaseField;
        
        private string imagenListadoField;
        
        private string imagenGrandeField;
        
        private string fechaInicialField;
        
        private string fechaFinalField;
        
        private string akamaiResAltaField;
        
        private string akamaiResMediaField;
        
        private string akamaiResBajaField;
        
        private string tituloField;
        
        private string meta_KeywordsField;
        
        private string meta_DescriptionField;
        
        private string codYoutubeNormalField;
        
        private string codYoutubeEmbedField;
        
        private string urlFriendlyField;
        
        private string imagenPequeniaField;
        
        private long ordenHomeField;
        
        private long alianzas_IdAlianzaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdMultimedia {
            get {
                return this.idMultimediaField;
            }
            set {
                this.idMultimediaField = value;
                this.RaisePropertyChanged("IdMultimedia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long Usuarios_IdUsuario {
            get {
                return this.usuarios_IdUsuarioField;
            }
            set {
                this.usuarios_IdUsuarioField = value;
                this.RaisePropertyChanged("Usuarios_IdUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FechaUltimaModificacion {
            get {
                return this.fechaUltimaModificacionField;
            }
            set {
                this.fechaUltimaModificacionField = value;
                this.RaisePropertyChanged("FechaUltimaModificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long SeccionesMultimedia_IdSeccion {
            get {
                return this.seccionesMultimedia_IdSeccionField;
            }
            set {
                this.seccionesMultimedia_IdSeccionField = value;
                this.RaisePropertyChanged("SeccionesMultimedia_IdSeccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long TiposMultimedia_IdTipo {
            get {
                return this.tiposMultimedia_IdTipoField;
            }
            set {
                this.tiposMultimedia_IdTipoField = value;
                this.RaisePropertyChanged("TiposMultimedia_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long TiposContenidoMultimedia_IdTipo {
            get {
                return this.tiposContenidoMultimedia_IdTipoField;
            }
            set {
                this.tiposContenidoMultimedia_IdTipoField = value;
                this.RaisePropertyChanged("TiposContenidoMultimedia_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long PublicarSitioWeb {
            get {
                return this.publicarSitioWebField;
            }
            set {
                this.publicarSitioWebField = value;
                this.RaisePropertyChanged("PublicarSitioWeb");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("FechaPublicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string FechaArchivo {
            get {
                return this.fechaArchivoField;
            }
            set {
                this.fechaArchivoField = value;
                this.RaisePropertyChanged("FechaArchivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string FuenteResAlta {
            get {
                return this.fuenteResAltaField;
            }
            set {
                this.fuenteResAltaField = value;
                this.RaisePropertyChanged("FuenteResAlta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string FuenteResMedia {
            get {
                return this.fuenteResMediaField;
            }
            set {
                this.fuenteResMediaField = value;
                this.RaisePropertyChanged("FuenteResMedia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string FuenteResBaja {
            get {
                return this.fuenteResBajaField;
            }
            set {
                this.fuenteResBajaField = value;
                this.RaisePropertyChanged("FuenteResBaja");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string FuenteRes {
            get {
                return this.fuenteResField;
            }
            set {
                this.fuenteResField = value;
                this.RaisePropertyChanged("FuenteRes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string Resolucion {
            get {
                return this.resolucionField;
            }
            set {
                this.resolucionField = value;
                this.RaisePropertyChanged("Resolucion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string FormatoDescarga {
            get {
                return this.formatoDescargaField;
            }
            set {
                this.formatoDescargaField = value;
                this.RaisePropertyChanged("FormatoDescarga");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public long EstadosPublicacion_IdEstado {
            get {
                return this.estadosPublicacion_IdEstadoField;
            }
            set {
                this.estadosPublicacion_IdEstadoField = value;
                this.RaisePropertyChanged("EstadosPublicacion_IdEstado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public long Ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("Ancho");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public long Alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
                this.RaisePropertyChanged("Alto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string Classid {
            get {
                return this.classidField;
            }
            set {
                this.classidField = value;
                this.RaisePropertyChanged("Classid");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string Codebase {
            get {
                return this.codebaseField;
            }
            set {
                this.codebaseField = value;
                this.RaisePropertyChanged("Codebase");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ImagenListado {
            get {
                return this.imagenListadoField;
            }
            set {
                this.imagenListadoField = value;
                this.RaisePropertyChanged("ImagenListado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string ImagenGrande {
            get {
                return this.imagenGrandeField;
            }
            set {
                this.imagenGrandeField = value;
                this.RaisePropertyChanged("ImagenGrande");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string FechaInicial {
            get {
                return this.fechaInicialField;
            }
            set {
                this.fechaInicialField = value;
                this.RaisePropertyChanged("FechaInicial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string FechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
                this.RaisePropertyChanged("FechaFinal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string AkamaiResAlta {
            get {
                return this.akamaiResAltaField;
            }
            set {
                this.akamaiResAltaField = value;
                this.RaisePropertyChanged("AkamaiResAlta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string AkamaiResMedia {
            get {
                return this.akamaiResMediaField;
            }
            set {
                this.akamaiResMediaField = value;
                this.RaisePropertyChanged("AkamaiResMedia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string AkamaiResBaja {
            get {
                return this.akamaiResBajaField;
            }
            set {
                this.akamaiResBajaField = value;
                this.RaisePropertyChanged("AkamaiResBaja");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Meta_Keywords {
            get {
                return this.meta_KeywordsField;
            }
            set {
                this.meta_KeywordsField = value;
                this.RaisePropertyChanged("Meta_Keywords");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Meta_Description {
            get {
                return this.meta_DescriptionField;
            }
            set {
                this.meta_DescriptionField = value;
                this.RaisePropertyChanged("Meta_Description");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string CodYoutubeNormal {
            get {
                return this.codYoutubeNormalField;
            }
            set {
                this.codYoutubeNormalField = value;
                this.RaisePropertyChanged("CodYoutubeNormal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string CodYoutubeEmbed {
            get {
                return this.codYoutubeEmbedField;
            }
            set {
                this.codYoutubeEmbedField = value;
                this.RaisePropertyChanged("CodYoutubeEmbed");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string UrlFriendly {
            get {
                return this.urlFriendlyField;
            }
            set {
                this.urlFriendlyField = value;
                this.RaisePropertyChanged("UrlFriendly");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string ImagenPequenia {
            get {
                return this.imagenPequeniaField;
            }
            set {
                this.imagenPequeniaField = value;
                this.RaisePropertyChanged("ImagenPequenia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public long OrdenHome {
            get {
                return this.ordenHomeField;
            }
            set {
                this.ordenHomeField = value;
                this.RaisePropertyChanged("OrdenHome");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public long Alianzas_IdAlianza {
            get {
                return this.alianzas_IdAlianzaField;
            }
            set {
                this.alianzas_IdAlianzaField = value;
                this.RaisePropertyChanged("Alianzas_IdAlianza");
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RespuestasSondeo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Sondeos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Autor))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Alianza))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Multimedia_Articulo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Articulos))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fotos_Galeria))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(GaleriaFotografica))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Multimedia))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GeneralProcess : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Documento_Articulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreField;
        
        private string urlField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Foros_Articulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long foros_IdForoField;
        
        private long articulos_IdArticuloField;
        
        private long ordenField;
        
        private string temaField;
        
        private string urlField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long Foros_IdForo {
            get {
                return this.foros_IdForoField;
            }
            set {
                this.foros_IdForoField = value;
                this.RaisePropertyChanged("Foros_IdForo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Articulos_IdArticulo {
            get {
                return this.articulos_IdArticuloField;
            }
            set {
                this.articulos_IdArticuloField = value;
                this.RaisePropertyChanged("Articulos_IdArticulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Tema {
            get {
                return this.temaField;
            }
            set {
                this.temaField = value;
                this.RaisePropertyChanged("Tema");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Galerias_Articulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idGaleriaField;
        
        private string nombreField;
        
        private string descripcionField;
        
        private long seccionesGaleria_IdSeccionField;
        
        private string imagenField;
        
        private string urlField;
        
        private string tituloField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdGaleria {
            get {
                return this.idGaleriaField;
            }
            set {
                this.idGaleriaField = value;
                this.RaisePropertyChanged("IdGaleria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long SeccionesGaleria_IdSeccion {
            get {
                return this.seccionesGaleria_IdSeccionField;
            }
            set {
                this.seccionesGaleria_IdSeccionField = value;
                this.RaisePropertyChanged("SeccionesGaleria_IdSeccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("Imagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Articulos_Relacionados : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idArticuloField;
        
        private string tituloField;
        
        private long ordenField;
        
        private string categoriaField;
        
        private bool enHomeField;
        
        private string urlField;
        
        private string resumenCortoField;
        
        private string imagenField;
        
        private string autorField;
        
        private string contenidoField;
        
        private string fechaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
                this.RaisePropertyChanged("IdArticulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("Categoria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool EnHome {
            get {
                return this.enHomeField;
            }
            set {
                this.enHomeField = value;
                this.RaisePropertyChanged("EnHome");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ResumenCorto {
            get {
                return this.resumenCortoField;
            }
            set {
                this.resumenCortoField = value;
                this.RaisePropertyChanged("ResumenCorto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("Imagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("Autor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("Contenido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Fecha {
            get {
                return this.fechaField;
            }
            set {
                this.fechaField = value;
                this.RaisePropertyChanged("Fecha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Imagenes_Articulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idImagenField;
        
        private long ordenField;
        
        private string piedeFotoField;
        
        private string autorField;
        
        private string nombreField;
        
        private int altoImagenField;
        
        private int anchoImagenField;
        
        private string nombreImagenField;
        
        private long idTipoImagenField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long IdImagen {
            get {
                return this.idImagenField;
            }
            set {
                this.idImagenField = value;
                this.RaisePropertyChanged("IdImagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PiedeFoto {
            get {
                return this.piedeFotoField;
            }
            set {
                this.piedeFotoField = value;
                this.RaisePropertyChanged("PiedeFoto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("Autor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AltoImagen {
            get {
                return this.altoImagenField;
            }
            set {
                this.altoImagenField = value;
                this.RaisePropertyChanged("AltoImagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int AnchoImagen {
            get {
                return this.anchoImagenField;
            }
            set {
                this.anchoImagenField = value;
                this.RaisePropertyChanged("AnchoImagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NombreImagen {
            get {
                return this.nombreImagenField;
            }
            set {
                this.nombreImagenField = value;
                this.RaisePropertyChanged("NombreImagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long IdTipoImagen {
            get {
                return this.idTipoImagenField;
            }
            set {
                this.idTipoImagenField = value;
                this.RaisePropertyChanged("IdTipoImagen");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespuestasSondeo : GeneralProcess {
        
        private long idRespuestaField;
        
        private long sondeos_IdSondeoField;
        
        private string respuestaField;
        
        private long ordenField;
        
        private double numeroVotosField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
                this.RaisePropertyChanged("IdRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long Sondeos_IdSondeo {
            get {
                return this.sondeos_IdSondeoField;
            }
            set {
                this.sondeos_IdSondeoField = value;
                this.RaisePropertyChanged("Sondeos_IdSondeo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Respuesta {
            get {
                return this.respuestaField;
            }
            set {
                this.respuestaField = value;
                this.RaisePropertyChanged("Respuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public double NumeroVotos {
            get {
                return this.numeroVotosField;
            }
            set {
                this.numeroVotosField = value;
                this.RaisePropertyChanged("NumeroVotos");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Sondeos : GeneralProcess {
        
        private long idSondeoField;
        
        private string fechaCreacionField;
        
        private string fechaUltimaModificacionField;
        
        private long usuarios_IdUsuarioField;
        
        private long tiposGrafica_IdTipoField;
        
        private string preguntaField;
        
        private long idRespuestaField;
        
        private long ediciones_IdEdicionField;
        
        private RespuestasSondeo[] respuestasSondeoField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdSondeo {
            get {
                return this.idSondeoField;
            }
            set {
                this.idSondeoField = value;
                this.RaisePropertyChanged("IdSondeo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FechaUltimaModificacion {
            get {
                return this.fechaUltimaModificacionField;
            }
            set {
                this.fechaUltimaModificacionField = value;
                this.RaisePropertyChanged("FechaUltimaModificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long Usuarios_IdUsuario {
            get {
                return this.usuarios_IdUsuarioField;
            }
            set {
                this.usuarios_IdUsuarioField = value;
                this.RaisePropertyChanged("Usuarios_IdUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long TiposGrafica_IdTipo {
            get {
                return this.tiposGrafica_IdTipoField;
            }
            set {
                this.tiposGrafica_IdTipoField = value;
                this.RaisePropertyChanged("TiposGrafica_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Pregunta {
            get {
                return this.preguntaField;
            }
            set {
                this.preguntaField = value;
                this.RaisePropertyChanged("Pregunta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long IdRespuesta {
            get {
                return this.idRespuestaField;
            }
            set {
                this.idRespuestaField = value;
                this.RaisePropertyChanged("IdRespuesta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long Ediciones_IdEdicion {
            get {
                return this.ediciones_IdEdicionField;
            }
            set {
                this.ediciones_IdEdicionField = value;
                this.RaisePropertyChanged("Ediciones_IdEdicion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=8)]
        public RespuestasSondeo[] RespuestasSondeo {
            get {
                return this.respuestasSondeoField;
            }
            set {
                this.respuestasSondeoField = value;
                this.RaisePropertyChanged("RespuestasSondeo");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Autor : GeneralProcess {
        
        private int idField;
        
        private string nombresField;
        
        private string apellidosField;
        
        private string urlAutorField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombres {
            get {
                return this.nombresField;
            }
            set {
                this.nombresField = value;
                this.RaisePropertyChanged("Nombres");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Apellidos {
            get {
                return this.apellidosField;
            }
            set {
                this.apellidosField = value;
                this.RaisePropertyChanged("Apellidos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UrlAutor {
            get {
                return this.urlAutorField;
            }
            set {
                this.urlAutorField = value;
                this.RaisePropertyChanged("UrlAutor");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Alianza : GeneralProcess {
        
        private int idAlianzaField;
        
        private string nombreAlianzaField;
        
        private string fotoField;
        
        private string scriptField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int IdAlianza {
            get {
                return this.idAlianzaField;
            }
            set {
                this.idAlianzaField = value;
                this.RaisePropertyChanged("IdAlianza");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string NombreAlianza {
            get {
                return this.nombreAlianzaField;
            }
            set {
                this.nombreAlianzaField = value;
                this.RaisePropertyChanged("NombreAlianza");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("Foto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Script {
            get {
                return this.scriptField;
            }
            set {
                this.scriptField = value;
                this.RaisePropertyChanged("Script");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Multimedia_Articulo : GeneralProcess {
        
        private long idMultimediaField;
        
        private string nombreField;
        
        private long seccionesMultimedia_IdSeccionField;
        
        private long tiposMultimedia_IdTipoField;
        
        private long tiposContenidoMultimedia_IdTipoField;
        
        private string fuenteResAltaField;
        
        private long anchoField;
        
        private long altoField;
        
        private string imagenListadoField;
        
        private string tituloField;
        
        private string urlField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdMultimedia {
            get {
                return this.idMultimediaField;
            }
            set {
                this.idMultimediaField = value;
                this.RaisePropertyChanged("IdMultimedia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public long SeccionesMultimedia_IdSeccion {
            get {
                return this.seccionesMultimedia_IdSeccionField;
            }
            set {
                this.seccionesMultimedia_IdSeccionField = value;
                this.RaisePropertyChanged("SeccionesMultimedia_IdSeccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long TiposMultimedia_IdTipo {
            get {
                return this.tiposMultimedia_IdTipoField;
            }
            set {
                this.tiposMultimedia_IdTipoField = value;
                this.RaisePropertyChanged("TiposMultimedia_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public long TiposContenidoMultimedia_IdTipo {
            get {
                return this.tiposContenidoMultimedia_IdTipoField;
            }
            set {
                this.tiposContenidoMultimedia_IdTipoField = value;
                this.RaisePropertyChanged("TiposContenidoMultimedia_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FuenteResAlta {
            get {
                return this.fuenteResAltaField;
            }
            set {
                this.fuenteResAltaField = value;
                this.RaisePropertyChanged("FuenteResAlta");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Ancho {
            get {
                return this.anchoField;
            }
            set {
                this.anchoField = value;
                this.RaisePropertyChanged("Ancho");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long Alto {
            get {
                return this.altoField;
            }
            set {
                this.altoField = value;
                this.RaisePropertyChanged("Alto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ImagenListado {
            get {
                return this.imagenListadoField;
            }
            set {
                this.imagenListadoField = value;
                this.RaisePropertyChanged("ImagenListado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string Url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
                this.RaisePropertyChanged("Url");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Articulos : GeneralProcess {
        
        private long idArticuloField;
        
        private string tituloField;
        
        private string anteTituloField;
        
        private string autorField;
        
        private string uRLField;
        
        private string resumenCortoField;
        
        private string resumenLargoField;
        
        private string contenidoField;
        
        private string descripcionField;
        
        private long usuarios_IdUsuarioField;
        
        private long ediciones_IdEdicionField;
        
        private long secciones_IdSeccionField;
        
        private long tiposArticulo_IdTipoField;
        
        private long plantillasDiagramacion_IdPlantillaField;
        
        private long tiposGrafica_IdTipoField;
        
        private long estadosPublicacion_IdEstadoField;
        
        private string fechaPublicacionField;
        
        private long horaPublicacionField;
        
        private string fechaArchivoField;
        
        private string fechaCreacionField;
        
        private string fechaUltimaModificacionField;
        
        private long estadoVisualizacionField;
        
        private long estadoCostoArticuloField;
        
        private long articuloPrincipalEdicionField;
        
        private long generaRSSField;
        
        private string palabraClaveField;
        
        private long tiposVinculo_IdTipoField;
        
        private long tiposTarget_IdTipoField;
        
        private string textoField;
        
        private string textoAlternoField;
        
        private string nombreImagenField;
        
        private string contenidoLimpioField;
        
        private long totalPalabrasField;
        
        private long galeriasField;
        
        private long documentosField;
        
        private long multimediasField;
        
        private long vinculosField;
        
        private long relacionadosField;
        
        private string fechaInicialField;
        
        private string fechaFinalField;
        
        private long totalEnPaginaField;
        
        private long paginaNumeroField;
        
        private long ordenField;
        
        private long tiposContenidoMultimedia_IdTipoField;
        
        private long maximoField;
        
        private string meta_KeywordsField;
        
        private string meta_DescriptionField;
        
        private long alianza_IdAlianzaField;
        
        private int autor_IdField;
        
        private Imagenes_Articulo[] lstImagenesField;
        
        private Articulos_Relacionados[] lstArticulosRelacionadosField;
        
        private Galerias_Articulo[] lstGaleriasField;
        
        private Multimedia_Articulo[] lstMultimediaField;
        
        private Articulos_Relacionados[] lstRecuadrosField;
        
        private Foros_Articulo[] lstForosField;
        
        private Articulos_Relacionados[] lstColumnistasField;
        
        private Documento_Articulo[] lstDocumentosField;
        
        private Alianza objAlianzaField;
        
        private Autor objAutorField;
        
        private Sondeos[] lstSondeosField;
        
        private string urlFriendlyField;
        
        private string urlFriendlyInglesField;
        
        private string dFechaPublicacionField;
        
        private string imagenPequeniaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdArticulo {
            get {
                return this.idArticuloField;
            }
            set {
                this.idArticuloField = value;
                this.RaisePropertyChanged("IdArticulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AnteTitulo {
            get {
                return this.anteTituloField;
            }
            set {
                this.anteTituloField = value;
                this.RaisePropertyChanged("AnteTitulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("Autor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
                this.RaisePropertyChanged("URL");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResumenCorto {
            get {
                return this.resumenCortoField;
            }
            set {
                this.resumenCortoField = value;
                this.RaisePropertyChanged("ResumenCorto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ResumenLargo {
            get {
                return this.resumenLargoField;
            }
            set {
                this.resumenLargoField = value;
                this.RaisePropertyChanged("ResumenLargo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Contenido {
            get {
                return this.contenidoField;
            }
            set {
                this.contenidoField = value;
                this.RaisePropertyChanged("Contenido");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public long Usuarios_IdUsuario {
            get {
                return this.usuarios_IdUsuarioField;
            }
            set {
                this.usuarios_IdUsuarioField = value;
                this.RaisePropertyChanged("Usuarios_IdUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public long Ediciones_IdEdicion {
            get {
                return this.ediciones_IdEdicionField;
            }
            set {
                this.ediciones_IdEdicionField = value;
                this.RaisePropertyChanged("Ediciones_IdEdicion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long Secciones_IdSeccion {
            get {
                return this.secciones_IdSeccionField;
            }
            set {
                this.secciones_IdSeccionField = value;
                this.RaisePropertyChanged("Secciones_IdSeccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public long TiposArticulo_IdTipo {
            get {
                return this.tiposArticulo_IdTipoField;
            }
            set {
                this.tiposArticulo_IdTipoField = value;
                this.RaisePropertyChanged("TiposArticulo_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public long PlantillasDiagramacion_IdPlantilla {
            get {
                return this.plantillasDiagramacion_IdPlantillaField;
            }
            set {
                this.plantillasDiagramacion_IdPlantillaField = value;
                this.RaisePropertyChanged("PlantillasDiagramacion_IdPlantilla");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public long TiposGrafica_IdTipo {
            get {
                return this.tiposGrafica_IdTipoField;
            }
            set {
                this.tiposGrafica_IdTipoField = value;
                this.RaisePropertyChanged("TiposGrafica_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public long EstadosPublicacion_IdEstado {
            get {
                return this.estadosPublicacion_IdEstadoField;
            }
            set {
                this.estadosPublicacion_IdEstadoField = value;
                this.RaisePropertyChanged("EstadosPublicacion_IdEstado");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string FechaPublicacion {
            get {
                return this.fechaPublicacionField;
            }
            set {
                this.fechaPublicacionField = value;
                this.RaisePropertyChanged("FechaPublicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public long HoraPublicacion {
            get {
                return this.horaPublicacionField;
            }
            set {
                this.horaPublicacionField = value;
                this.RaisePropertyChanged("HoraPublicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string FechaArchivo {
            get {
                return this.fechaArchivoField;
            }
            set {
                this.fechaArchivoField = value;
                this.RaisePropertyChanged("FechaArchivo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string FechaUltimaModificacion {
            get {
                return this.fechaUltimaModificacionField;
            }
            set {
                this.fechaUltimaModificacionField = value;
                this.RaisePropertyChanged("FechaUltimaModificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public long EstadoVisualizacion {
            get {
                return this.estadoVisualizacionField;
            }
            set {
                this.estadoVisualizacionField = value;
                this.RaisePropertyChanged("EstadoVisualizacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public long EstadoCostoArticulo {
            get {
                return this.estadoCostoArticuloField;
            }
            set {
                this.estadoCostoArticuloField = value;
                this.RaisePropertyChanged("EstadoCostoArticulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public long ArticuloPrincipalEdicion {
            get {
                return this.articuloPrincipalEdicionField;
            }
            set {
                this.articuloPrincipalEdicionField = value;
                this.RaisePropertyChanged("ArticuloPrincipalEdicion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public long GeneraRSS {
            get {
                return this.generaRSSField;
            }
            set {
                this.generaRSSField = value;
                this.RaisePropertyChanged("GeneraRSS");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string PalabraClave {
            get {
                return this.palabraClaveField;
            }
            set {
                this.palabraClaveField = value;
                this.RaisePropertyChanged("PalabraClave");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public long TiposVinculo_IdTipo {
            get {
                return this.tiposVinculo_IdTipoField;
            }
            set {
                this.tiposVinculo_IdTipoField = value;
                this.RaisePropertyChanged("TiposVinculo_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public long TiposTarget_IdTipo {
            get {
                return this.tiposTarget_IdTipoField;
            }
            set {
                this.tiposTarget_IdTipoField = value;
                this.RaisePropertyChanged("TiposTarget_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string Texto {
            get {
                return this.textoField;
            }
            set {
                this.textoField = value;
                this.RaisePropertyChanged("Texto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string TextoAlterno {
            get {
                return this.textoAlternoField;
            }
            set {
                this.textoAlternoField = value;
                this.RaisePropertyChanged("TextoAlterno");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string NombreImagen {
            get {
                return this.nombreImagenField;
            }
            set {
                this.nombreImagenField = value;
                this.RaisePropertyChanged("NombreImagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ContenidoLimpio {
            get {
                return this.contenidoLimpioField;
            }
            set {
                this.contenidoLimpioField = value;
                this.RaisePropertyChanged("ContenidoLimpio");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public long TotalPalabras {
            get {
                return this.totalPalabrasField;
            }
            set {
                this.totalPalabrasField = value;
                this.RaisePropertyChanged("TotalPalabras");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public long Galerias {
            get {
                return this.galeriasField;
            }
            set {
                this.galeriasField = value;
                this.RaisePropertyChanged("Galerias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public long Documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
                this.RaisePropertyChanged("Documentos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public long Multimedias {
            get {
                return this.multimediasField;
            }
            set {
                this.multimediasField = value;
                this.RaisePropertyChanged("Multimedias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public long Vinculos {
            get {
                return this.vinculosField;
            }
            set {
                this.vinculosField = value;
                this.RaisePropertyChanged("Vinculos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public long Relacionados {
            get {
                return this.relacionadosField;
            }
            set {
                this.relacionadosField = value;
                this.RaisePropertyChanged("Relacionados");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string FechaInicial {
            get {
                return this.fechaInicialField;
            }
            set {
                this.fechaInicialField = value;
                this.RaisePropertyChanged("FechaInicial");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string FechaFinal {
            get {
                return this.fechaFinalField;
            }
            set {
                this.fechaFinalField = value;
                this.RaisePropertyChanged("FechaFinal");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public long TotalEnPagina {
            get {
                return this.totalEnPaginaField;
            }
            set {
                this.totalEnPaginaField = value;
                this.RaisePropertyChanged("TotalEnPagina");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public long PaginaNumero {
            get {
                return this.paginaNumeroField;
            }
            set {
                this.paginaNumeroField = value;
                this.RaisePropertyChanged("PaginaNumero");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public long Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public long TiposContenidoMultimedia_IdTipo {
            get {
                return this.tiposContenidoMultimedia_IdTipoField;
            }
            set {
                this.tiposContenidoMultimedia_IdTipoField = value;
                this.RaisePropertyChanged("TiposContenidoMultimedia_IdTipo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public long Maximo {
            get {
                return this.maximoField;
            }
            set {
                this.maximoField = value;
                this.RaisePropertyChanged("Maximo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string Meta_Keywords {
            get {
                return this.meta_KeywordsField;
            }
            set {
                this.meta_KeywordsField = value;
                this.RaisePropertyChanged("Meta_Keywords");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string Meta_Description {
            get {
                return this.meta_DescriptionField;
            }
            set {
                this.meta_DescriptionField = value;
                this.RaisePropertyChanged("Meta_Description");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public long Alianza_IdAlianza {
            get {
                return this.alianza_IdAlianzaField;
            }
            set {
                this.alianza_IdAlianzaField = value;
                this.RaisePropertyChanged("Alianza_IdAlianza");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public int Autor_Id {
            get {
                return this.autor_IdField;
            }
            set {
                this.autor_IdField = value;
                this.RaisePropertyChanged("Autor_Id");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=49)]
        public Imagenes_Articulo[] lstImagenes {
            get {
                return this.lstImagenesField;
            }
            set {
                this.lstImagenesField = value;
                this.RaisePropertyChanged("lstImagenes");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=50)]
        public Articulos_Relacionados[] LstArticulosRelacionados {
            get {
                return this.lstArticulosRelacionadosField;
            }
            set {
                this.lstArticulosRelacionadosField = value;
                this.RaisePropertyChanged("LstArticulosRelacionados");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=51)]
        public Galerias_Articulo[] lstGalerias {
            get {
                return this.lstGaleriasField;
            }
            set {
                this.lstGaleriasField = value;
                this.RaisePropertyChanged("lstGalerias");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=52)]
        public Multimedia_Articulo[] lstMultimedia {
            get {
                return this.lstMultimediaField;
            }
            set {
                this.lstMultimediaField = value;
                this.RaisePropertyChanged("lstMultimedia");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=53)]
        public Articulos_Relacionados[] lstRecuadros {
            get {
                return this.lstRecuadrosField;
            }
            set {
                this.lstRecuadrosField = value;
                this.RaisePropertyChanged("lstRecuadros");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=54)]
        public Foros_Articulo[] LstForos {
            get {
                return this.lstForosField;
            }
            set {
                this.lstForosField = value;
                this.RaisePropertyChanged("LstForos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=55)]
        public Articulos_Relacionados[] LstColumnistas {
            get {
                return this.lstColumnistasField;
            }
            set {
                this.lstColumnistasField = value;
                this.RaisePropertyChanged("LstColumnistas");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=56)]
        public Documento_Articulo[] LstDocumentos {
            get {
                return this.lstDocumentosField;
            }
            set {
                this.lstDocumentosField = value;
                this.RaisePropertyChanged("LstDocumentos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public Alianza ObjAlianza {
            get {
                return this.objAlianzaField;
            }
            set {
                this.objAlianzaField = value;
                this.RaisePropertyChanged("ObjAlianza");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public Autor ObjAutor {
            get {
                return this.objAutorField;
            }
            set {
                this.objAutorField = value;
                this.RaisePropertyChanged("ObjAutor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=59)]
        public Sondeos[] LstSondeos {
            get {
                return this.lstSondeosField;
            }
            set {
                this.lstSondeosField = value;
                this.RaisePropertyChanged("LstSondeos");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public string UrlFriendly {
            get {
                return this.urlFriendlyField;
            }
            set {
                this.urlFriendlyField = value;
                this.RaisePropertyChanged("UrlFriendly");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string UrlFriendlyIngles {
            get {
                return this.urlFriendlyInglesField;
            }
            set {
                this.urlFriendlyInglesField = value;
                this.RaisePropertyChanged("UrlFriendlyIngles");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string DFechaPublicacion {
            get {
                return this.dFechaPublicacionField;
            }
            set {
                this.dFechaPublicacionField = value;
                this.RaisePropertyChanged("DFechaPublicacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string ImagenPequenia {
            get {
                return this.imagenPequeniaField;
            }
            set {
                this.imagenPequeniaField = value;
                this.RaisePropertyChanged("ImagenPequenia");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Fotos_Galeria : GeneralProcess {
        
        private long idFotoField;
        
        private long galeriasFotograficas_IdGaleriaField;
        
        private string fotoGrandeField;
        
        private string fotoPequeñaField;
        
        private string piedeFotoField;
        
        private string autorField;
        
        private long ordenField;
        
        private string fechaCreacionField;
        
        private long usuarios_IdUsuarioField;
        
        private string fechaUltimaModificacionField;
        
        private int altoFotoGrandeField;
        
        private int anchoFotoGrandeField;
        
        private int altoFotoPequeñaField;
        
        private int anchoFotoPequeñaField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdFoto {
            get {
                return this.idFotoField;
            }
            set {
                this.idFotoField = value;
                this.RaisePropertyChanged("IdFoto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public long GaleriasFotograficas_IdGaleria {
            get {
                return this.galeriasFotograficas_IdGaleriaField;
            }
            set {
                this.galeriasFotograficas_IdGaleriaField = value;
                this.RaisePropertyChanged("GaleriasFotograficas_IdGaleria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string FotoGrande {
            get {
                return this.fotoGrandeField;
            }
            set {
                this.fotoGrandeField = value;
                this.RaisePropertyChanged("FotoGrande");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string FotoPequeña {
            get {
                return this.fotoPequeñaField;
            }
            set {
                this.fotoPequeñaField = value;
                this.RaisePropertyChanged("FotoPequeña");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PiedeFoto {
            get {
                return this.piedeFotoField;
            }
            set {
                this.piedeFotoField = value;
                this.RaisePropertyChanged("PiedeFoto");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Autor {
            get {
                return this.autorField;
            }
            set {
                this.autorField = value;
                this.RaisePropertyChanged("Autor");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public long Orden {
            get {
                return this.ordenField;
            }
            set {
                this.ordenField = value;
                this.RaisePropertyChanged("Orden");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public long Usuarios_IdUsuario {
            get {
                return this.usuarios_IdUsuarioField;
            }
            set {
                this.usuarios_IdUsuarioField = value;
                this.RaisePropertyChanged("Usuarios_IdUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string FechaUltimaModificacion {
            get {
                return this.fechaUltimaModificacionField;
            }
            set {
                this.fechaUltimaModificacionField = value;
                this.RaisePropertyChanged("FechaUltimaModificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public int AltoFotoGrande {
            get {
                return this.altoFotoGrandeField;
            }
            set {
                this.altoFotoGrandeField = value;
                this.RaisePropertyChanged("AltoFotoGrande");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int AnchoFotoGrande {
            get {
                return this.anchoFotoGrandeField;
            }
            set {
                this.anchoFotoGrandeField = value;
                this.RaisePropertyChanged("AnchoFotoGrande");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public int AltoFotoPequeña {
            get {
                return this.altoFotoPequeñaField;
            }
            set {
                this.altoFotoPequeñaField = value;
                this.RaisePropertyChanged("AltoFotoPequeña");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int AnchoFotoPequeña {
            get {
                return this.anchoFotoPequeñaField;
            }
            set {
                this.anchoFotoPequeñaField = value;
                this.RaisePropertyChanged("AnchoFotoPequeña");
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class GaleriaFotografica : GeneralProcess {
        
        private long idGaleriaField;
        
        private string nombreField;
        
        private string tituloField;
        
        private string descripcionField;
        
        private string fechaCreacionField;
        
        private long usuarios_IdUsuarioField;
        
        private string fechaUltimaModificacionField;
        
        private long seccionesGaleria_IdSeccionField;
        
        private string imagenField;
        
        private string imagen_PequeñaField;
        
        private string urlFriendlyField;
        
        private long ordenHomeField;
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long IdGaleria {
            get {
                return this.idGaleriaField;
            }
            set {
                this.idGaleriaField = value;
                this.RaisePropertyChanged("IdGaleria");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("Nombre");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Titulo {
            get {
                return this.tituloField;
            }
            set {
                this.tituloField = value;
                this.RaisePropertyChanged("Titulo");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("Descripcion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string FechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("FechaCreacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public long Usuarios_IdUsuario {
            get {
                return this.usuarios_IdUsuarioField;
            }
            set {
                this.usuarios_IdUsuarioField = value;
                this.RaisePropertyChanged("Usuarios_IdUsuario");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FechaUltimaModificacion {
            get {
                return this.fechaUltimaModificacionField;
            }
            set {
                this.fechaUltimaModificacionField = value;
                this.RaisePropertyChanged("FechaUltimaModificacion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public long SeccionesGaleria_IdSeccion {
            get {
                return this.seccionesGaleria_IdSeccionField;
            }
            set {
                this.seccionesGaleria_IdSeccionField = value;
                this.RaisePropertyChanged("SeccionesGaleria_IdSeccion");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Imagen {
            get {
                return this.imagenField;
            }
            set {
                this.imagenField = value;
                this.RaisePropertyChanged("Imagen");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Imagen_Pequeña {
            get {
                return this.imagen_PequeñaField;
            }
            set {
                this.imagen_PequeñaField = value;
                this.RaisePropertyChanged("Imagen_Pequeña");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string UrlFriendly {
            get {
                return this.urlFriendlyField;
            }
            set {
                this.urlFriendlyField = value;
                this.RaisePropertyChanged("UrlFriendly");
            }
        }
        
        /// <comentarios/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public long OrdenHome {
            get {
                return this.ordenHomeField;
            }
            set {
                this.ordenHomeField = value;
                this.RaisePropertyChanged("OrdenHome");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ws_BusquedasSoapChannel : ServiceSemana.ServicesSemana.ws_BusquedasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ws_BusquedasSoapClient : System.ServiceModel.ClientBase<ServiceSemana.ServicesSemana.ws_BusquedasSoap>, ServiceSemana.ServicesSemana.ws_BusquedasSoap {
        
        public ws_BusquedasSoapClient() {
        }
        
        public ws_BusquedasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ws_BusquedasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_BusquedasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ws_BusquedasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceSemana.ServicesSemana.Multimedia[] lst_MultimediasByParameter(int pageNumber, int pageSize, string filterFind, int idSeccion, int idTipoMultimedia) {
            return base.Channel.lst_MultimediasByParameter(pageNumber, pageSize, filterFind, idSeccion, idTipoMultimedia);
        }
        
        public ServiceSemana.ServicesSemana.GaleriaFotografica[] lst_GaleriaFindParameterPageIndex(int pageNumber, int pageSize, string filterFind, int idSeccion) {
            return base.Channel.lst_GaleriaFindParameterPageIndex(pageNumber, pageSize, filterFind, idSeccion);
        }
        
        public ServiceSemana.ServicesSemana.Fotos_Galeria[] lst_GaleriaFindPhotos(int idGaleria) {
            return base.Channel.lst_GaleriaFindPhotos(idGaleria);
        }
        
        public ServiceSemana.ServicesSemana.Articulos[] lst_ArticuloFindParameterPageIndex(int pageNumber, int pageSize, string filterFind, int idSeccion) {
            return base.Channel.lst_ArticuloFindParameterPageIndex(pageNumber, pageSize, filterFind, idSeccion);
        }
        
        public ServiceSemana.ServicesSemana.Articulos[] lst_ArticuloFindAuthorPageIndex(int pageNumber, int pageSize, int idAuthor) {
            return base.Channel.lst_ArticuloFindAuthorPageIndex(pageNumber, pageSize, idAuthor);
        }
        
        public ServiceSemana.ServicesSemana.Articulos[] lst_CaricaturasFindParameterPageIndex(int pageNumber, int pageSize, int idSeccion, int idEdicion) {
            return base.Channel.lst_CaricaturasFindParameterPageIndex(pageNumber, pageSize, idSeccion, idEdicion);
        }
        
        public string lst_NotificacionUltimosCreados() {
            return base.Channel.lst_NotificacionUltimosCreados();
        }
    }
}
