//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSemana.ServiceSemana2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceSemana2.wsItemSoap")]
    public interface wsItemSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findItem", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.findItemResponse findItem(ServiceSemana.ServiceSemana2.findItemRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItems", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getItemsResponse getItems(ServiceSemana.ServiceSemana2.getItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsSecciones", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getItemsSeccionesResponse getItemsSecciones(ServiceSemana.ServiceSemana2.getItemsSeccionesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsByEdicion", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getItemsByEdicionResponse getItemsByEdicion(ServiceSemana.ServiceSemana2.getItemsByEdicionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsBySeccion", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getItemsBySeccionResponse getItemsBySeccion(ServiceSemana.ServiceSemana2.getItemsBySeccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsByEdicionActualSeccion", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionResponse getItemsByEdicionActualSeccion(ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsBySeccionRecursiva", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaResponse getItemsBySeccionRecursiva(ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTerminos", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getTerminosResponse getTerminos(ServiceSemana.ServiceSemana2.getTerminosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreguntas", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getPreguntasResponse getPreguntas(ServiceSemana.ServiceSemana2.getPreguntasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPregunta", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getPreguntaResponse getPregunta(ServiceSemana.ServiceSemana2.getPreguntaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPregunta", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.addPreguntaResponse addPregunta(ServiceSemana.ServiceSemana2.addPreguntaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNextMultimedia", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getNextMultimediaResponse getNextMultimedia(ServiceSemana.ServiceSemana2.getNextMultimediaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getImage", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getImageResponse getImage(ServiceSemana.ServiceSemana2.getImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGaleria", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getGaleriaResponse getGaleria(ServiceSemana.ServiceSemana2.getGaleriaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGalery", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getGaleryResponse getGalery(ServiceSemana.ServiceSemana2.getGaleryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFotosHome", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getFotosHomeResponse getFotosHome(ServiceSemana.ServiceSemana2.getFotosHomeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addVote", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.addVoteResponse addVote(ServiceSemana.ServiceSemana2.addVoteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMultimediasByAdvancedSearching", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingResponse getMultimediasByAdvancedSearching(ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMultimedias", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getMultimediasResponse getMultimedias(ServiceSemana.ServiceSemana2.getMultimediasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGalerias", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getGaleriasResponse getGalerias(ServiceSemana.ServiceSemana2.getGaleriasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHorocopos", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getHorocoposResponse getHorocopos(ServiceSemana.ServiceSemana2.getHorocoposRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVersus", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.getVersusResponse getVersus(ServiceSemana.ServiceSemana2.getVersusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findItemsByAuthor", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.findItemsByAuthorResponse findItemsByAuthor(ServiceSemana.ServiceSemana2.findItemsByAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/lstCrucigramas", ReplyAction="*")]
        ServiceSemana.ServiceSemana2.lstCrucigramasResponse lstCrucigramas(ServiceSemana.ServiceSemana2.lstCrucigramasRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findItem", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.findItemRequestBody Body;
        
        public findItemRequest() {
        }
        
        public findItemRequest(ServiceSemana.ServiceSemana2.findItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public findItemRequestBody() {
        }
        
        public findItemRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.findItemResponseBody Body;
        
        public findItemResponse() {
        }
        
        public findItemResponse(ServiceSemana.ServiceSemana2.findItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string findItemResult;
        
        public findItemResponseBody() {
        }
        
        public findItemResponseBody(string findItemResult) {
            this.findItemResult = findItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItems", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsRequestBody Body;
        
        public getItemsRequest() {
        }
        
        public getItemsRequest(ServiceSemana.ServiceSemana2.getItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool asc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idTipoItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool calculadora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int pageSize;
        
        public getItemsRequestBody() {
        }
        
        public getItemsRequestBody(string title, string sortBy, bool asc, int idTipoItem, int idSeccion, bool calculadora, int pageNumber, int pageSize) {
            this.title = title;
            this.sortBy = sortBy;
            this.asc = asc;
            this.idTipoItem = idTipoItem;
            this.idSeccion = idSeccion;
            this.calculadora = calculadora;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsResponseBody Body;
        
        public getItemsResponse() {
        }
        
        public getItemsResponse(ServiceSemana.ServiceSemana2.getItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsResult;
        
        public getItemsResponseBody() {
        }
        
        public getItemsResponseBody(string getItemsResult) {
            this.getItemsResult = getItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsSeccionesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsSecciones", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsSeccionesRequestBody Body;
        
        public getItemsSeccionesRequest() {
        }
        
        public getItemsSeccionesRequest(ServiceSemana.ServiceSemana2.getItemsSeccionesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsSeccionesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool asc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idTipoItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string idSecciones;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pageSize;
        
        public getItemsSeccionesRequestBody() {
        }
        
        public getItemsSeccionesRequestBody(string title, string sortBy, bool asc, int idTipoItem, string idSecciones, int pageNumber, int pageSize) {
            this.title = title;
            this.sortBy = sortBy;
            this.asc = asc;
            this.idTipoItem = idTipoItem;
            this.idSecciones = idSecciones;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsSeccionesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsSeccionesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsSeccionesResponseBody Body;
        
        public getItemsSeccionesResponse() {
        }
        
        public getItemsSeccionesResponse(ServiceSemana.ServiceSemana2.getItemsSeccionesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsSeccionesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsSeccionesResult;
        
        public getItemsSeccionesResponseBody() {
        }
        
        public getItemsSeccionesResponseBody(string getItemsSeccionesResult) {
            this.getItemsSeccionesResult = getItemsSeccionesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsByEdicionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsByEdicion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsByEdicionRequestBody Body;
        
        public getItemsByEdicionRequest() {
        }
        
        public getItemsByEdicionRequest(ServiceSemana.ServiceSemana2.getItemsByEdicionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsByEdicionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEdicion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageSize;
        
        public getItemsByEdicionRequestBody() {
        }
        
        public getItemsByEdicionRequestBody(int idEdicion, int pageNumber, int pageSize) {
            this.idEdicion = idEdicion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsByEdicionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsByEdicionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsByEdicionResponseBody Body;
        
        public getItemsByEdicionResponse() {
        }
        
        public getItemsByEdicionResponse(ServiceSemana.ServiceSemana2.getItemsByEdicionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsByEdicionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsByEdicionResult;
        
        public getItemsByEdicionResponseBody() {
        }
        
        public getItemsByEdicionResponseBody(string getItemsByEdicionResult) {
            this.getItemsByEdicionResult = getItemsByEdicionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsBySeccionRequestBody Body;
        
        public getItemsBySeccionRequest() {
        }
        
        public getItemsBySeccionRequest(ServiceSemana.ServiceSemana2.getItemsBySeccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string what;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool bImpresa;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool bOnLine;
        
        public getItemsBySeccionRequestBody() {
        }
        
        public getItemsBySeccionRequestBody(string what, int idSeccion, int pageNumber, int pageSize, bool bImpresa, bool bOnLine) {
            this.what = what;
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
            this.bImpresa = bImpresa;
            this.bOnLine = bOnLine;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsBySeccionResponseBody Body;
        
        public getItemsBySeccionResponse() {
        }
        
        public getItemsBySeccionResponse(ServiceSemana.ServiceSemana2.getItemsBySeccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsBySeccionResult;
        
        public getItemsBySeccionResponseBody() {
        }
        
        public getItemsBySeccionResponseBody(string getItemsBySeccionResult) {
            this.getItemsBySeccionResult = getItemsBySeccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsByEdicionActualSeccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsByEdicionActualSeccion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionRequestBody Body;
        
        public getItemsByEdicionActualSeccionRequest() {
        }
        
        public getItemsByEdicionActualSeccionRequest(ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsByEdicionActualSeccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageSize;
        
        public getItemsByEdicionActualSeccionRequestBody() {
        }
        
        public getItemsByEdicionActualSeccionRequestBody(int idSeccion, int pageNumber, int pageSize) {
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsByEdicionActualSeccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsByEdicionActualSeccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionResponseBody Body;
        
        public getItemsByEdicionActualSeccionResponse() {
        }
        
        public getItemsByEdicionActualSeccionResponse(ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsByEdicionActualSeccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsByEdicionActualSeccionResult;
        
        public getItemsByEdicionActualSeccionResponseBody() {
        }
        
        public getItemsByEdicionActualSeccionResponseBody(string getItemsByEdicionActualSeccionResult) {
            this.getItemsByEdicionActualSeccionResult = getItemsByEdicionActualSeccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionRecursivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccionRecursiva", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaRequestBody Body;
        
        public getItemsBySeccionRecursivaRequest() {
        }
        
        public getItemsBySeccionRecursivaRequest(ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionRecursivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string what;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        public getItemsBySeccionRecursivaRequestBody() {
        }
        
        public getItemsBySeccionRecursivaRequestBody(string what, int idSeccion, int pageNumber, int pageSize) {
            this.what = what;
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionRecursivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccionRecursivaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaResponseBody Body;
        
        public getItemsBySeccionRecursivaResponse() {
        }
        
        public getItemsBySeccionRecursivaResponse(ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionRecursivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsBySeccionRecursivaResult;
        
        public getItemsBySeccionRecursivaResponseBody() {
        }
        
        public getItemsBySeccionRecursivaResponseBody(string getItemsBySeccionRecursivaResult) {
            this.getItemsBySeccionRecursivaResult = getItemsBySeccionRecursivaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTerminosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTerminos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getTerminosRequestBody Body;
        
        public getTerminosRequest() {
        }
        
        public getTerminosRequest(ServiceSemana.ServiceSemana2.getTerminosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTerminosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageSize;
        
        public getTerminosRequestBody() {
        }
        
        public getTerminosRequestBody(string title, int pageNumber, int pageSize) {
            this.title = title;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTerminosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTerminosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getTerminosResponseBody Body;
        
        public getTerminosResponse() {
        }
        
        public getTerminosResponse(ServiceSemana.ServiceSemana2.getTerminosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTerminosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTerminosResult;
        
        public getTerminosResponseBody() {
        }
        
        public getTerminosResponseBody(string getTerminosResult) {
            this.getTerminosResult = getTerminosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreguntas", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getPreguntasRequestBody Body;
        
        public getPreguntasRequest() {
        }
        
        public getPreguntasRequest(ServiceSemana.ServiceSemana2.getPreguntasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        public getPreguntasRequestBody() {
        }
        
        public getPreguntasRequestBody(string title, int idSeccion, int pageNumber, int pageSize) {
            this.title = title;
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreguntasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getPreguntasResponseBody Body;
        
        public getPreguntasResponse() {
        }
        
        public getPreguntasResponse(ServiceSemana.ServiceSemana2.getPreguntasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPreguntasResult;
        
        public getPreguntasResponseBody() {
        }
        
        public getPreguntasResponseBody(string getPreguntasResult) {
            this.getPreguntasResult = getPreguntasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPregunta", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getPreguntaRequestBody Body;
        
        public getPreguntaRequest() {
        }
        
        public getPreguntaRequest(ServiceSemana.ServiceSemana2.getPreguntaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idItem;
        
        public getPreguntaRequestBody() {
        }
        
        public getPreguntaRequestBody(int idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreguntaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getPreguntaResponseBody Body;
        
        public getPreguntaResponse() {
        }
        
        public getPreguntaResponse(ServiceSemana.ServiceSemana2.getPreguntaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPreguntaResult;
        
        public getPreguntaResponseBody() {
        }
        
        public getPreguntaResponseBody(string getPreguntaResult) {
            this.getPreguntaResult = getPreguntaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPreguntaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPregunta", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.addPreguntaRequestBody Body;
        
        public addPreguntaRequest() {
        }
        
        public addPreguntaRequest(ServiceSemana.ServiceSemana2.addPreguntaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPreguntaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string autor;
        
        public addPreguntaRequestBody() {
        }
        
        public addPreguntaRequestBody(string title, int idSeccion, string autor) {
            this.title = title;
            this.idSeccion = idSeccion;
            this.autor = autor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPreguntaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPreguntaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.addPreguntaResponseBody Body;
        
        public addPreguntaResponse() {
        }
        
        public addPreguntaResponse(ServiceSemana.ServiceSemana2.addPreguntaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPreguntaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addPreguntaResult;
        
        public addPreguntaResponseBody() {
        }
        
        public addPreguntaResponseBody(string addPreguntaResult) {
            this.addPreguntaResult = addPreguntaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextMultimediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextMultimedia", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getNextMultimediaRequestBody Body;
        
        public getNextMultimediaRequest() {
        }
        
        public getNextMultimediaRequest(ServiceSemana.ServiceSemana2.getNextMultimediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextMultimediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idItem;
        
        public getNextMultimediaRequestBody() {
        }
        
        public getNextMultimediaRequestBody(int idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextMultimediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextMultimediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getNextMultimediaResponseBody Body;
        
        public getNextMultimediaResponse() {
        }
        
        public getNextMultimediaResponse(ServiceSemana.ServiceSemana2.getNextMultimediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextMultimediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNextMultimediaResult;
        
        public getNextMultimediaResponseBody() {
        }
        
        public getNextMultimediaResponseBody(string getNextMultimediaResult) {
            this.getNextMultimediaResult = getNextMultimediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getImage", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getImageRequestBody Body;
        
        public getImageRequest() {
        }
        
        public getImageRequest(ServiceSemana.ServiceSemana2.getImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idsItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idTipoImagen;
        
        public getImageRequestBody() {
        }
        
        public getImageRequestBody(string idsItem, int idTipoImagen) {
            this.idsItem = idsItem;
            this.idTipoImagen = idTipoImagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getImageResponseBody Body;
        
        public getImageResponse() {
        }
        
        public getImageResponse(ServiceSemana.ServiceSemana2.getImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getImageResult;
        
        public getImageResponseBody() {
        }
        
        public getImageResponseBody(string getImageResult) {
            this.getImageResult = getImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleria", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getGaleriaRequestBody Body;
        
        public getGaleriaRequest() {
        }
        
        public getGaleriaRequest(ServiceSemana.ServiceSemana2.getGaleriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTipoImagen;
        
        public getGaleriaRequestBody() {
        }
        
        public getGaleriaRequestBody(string idItem, string idTipoImagen) {
            this.idItem = idItem;
            this.idTipoImagen = idTipoImagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getGaleriaResponseBody Body;
        
        public getGaleriaResponse() {
        }
        
        public getGaleriaResponse(ServiceSemana.ServiceSemana2.getGaleriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGaleriaResult;
        
        public getGaleriaResponseBody() {
        }
        
        public getGaleriaResponseBody(string getGaleriaResult) {
            this.getGaleriaResult = getGaleriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGalery", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getGaleryRequestBody Body;
        
        public getGaleryRequest() {
        }
        
        public getGaleryRequest(ServiceSemana.ServiceSemana2.getGaleryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idItem;
        
        public getGaleryRequestBody() {
        }
        
        public getGaleryRequestBody(string idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getGaleryResponseBody Body;
        
        public getGaleryResponse() {
        }
        
        public getGaleryResponse(ServiceSemana.ServiceSemana2.getGaleryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGaleryResult;
        
        public getGaleryResponseBody() {
        }
        
        public getGaleryResponseBody(string getGaleryResult) {
            this.getGaleryResult = getGaleryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFotosHomeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFotosHome", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getFotosHomeRequestBody Body;
        
        public getFotosHomeRequest() {
        }
        
        public getFotosHomeRequest(ServiceSemana.ServiceSemana2.getFotosHomeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFotosHomeRequestBody {
        
        public getFotosHomeRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFotosHomeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFotosHomeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getFotosHomeResponseBody Body;
        
        public getFotosHomeResponse() {
        }
        
        public getFotosHomeResponse(ServiceSemana.ServiceSemana2.getFotosHomeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFotosHomeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFotosHomeResult;
        
        public getFotosHomeResponseBody() {
        }
        
        public getFotosHomeResponseBody(string getFotosHomeResult) {
            this.getFotosHomeResult = getFotosHomeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addVoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addVote", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.addVoteRequestBody Body;
        
        public addVoteRequest() {
        }
        
        public addVoteRequest(ServiceSemana.ServiceSemana2.addVoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addVoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEncuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idRespuesta;
        
        public addVoteRequestBody() {
        }
        
        public addVoteRequestBody(int idEncuesta, int idRespuesta) {
            this.idEncuesta = idEncuesta;
            this.idRespuesta = idRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addVoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addVoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.addVoteResponseBody Body;
        
        public addVoteResponse() {
        }
        
        public addVoteResponse(ServiceSemana.ServiceSemana2.addVoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addVoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addVoteResult;
        
        public addVoteResponseBody() {
        }
        
        public addVoteResponseBody(string addVoteResult) {
            this.addVoteResult = addVoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMultimediasByAdvancedSearchingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMultimediasByAdvancedSearching", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingRequestBody Body;
        
        public getMultimediasByAdvancedSearchingRequest() {
        }
        
        public getMultimediasByAdvancedSearchingRequest(ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMultimediasByAdvancedSearchingRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool asc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idtipoMultimedia;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int pageSize;
        
        public getMultimediasByAdvancedSearchingRequestBody() {
        }
        
        public getMultimediasByAdvancedSearchingRequestBody(string title, string sortBy, bool asc, int idtipoMultimedia, int pageNumber, int pageSize) {
            this.title = title;
            this.sortBy = sortBy;
            this.asc = asc;
            this.idtipoMultimedia = idtipoMultimedia;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMultimediasByAdvancedSearchingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMultimediasByAdvancedSearchingResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingResponseBody Body;
        
        public getMultimediasByAdvancedSearchingResponse() {
        }
        
        public getMultimediasByAdvancedSearchingResponse(ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMultimediasByAdvancedSearchingResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMultimediasByAdvancedSearchingResult;
        
        public getMultimediasByAdvancedSearchingResponseBody() {
        }
        
        public getMultimediasByAdvancedSearchingResponseBody(string getMultimediasByAdvancedSearchingResult) {
            this.getMultimediasByAdvancedSearchingResult = getMultimediasByAdvancedSearchingResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMultimediasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMultimedias", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getMultimediasRequestBody Body;
        
        public getMultimediasRequest() {
        }
        
        public getMultimediasRequest(ServiceSemana.ServiceSemana2.getMultimediasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMultimediasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageSize;
        
        public getMultimediasRequestBody() {
        }
        
        public getMultimediasRequestBody(int pageNumber, int pageSize) {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMultimediasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMultimediasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getMultimediasResponseBody Body;
        
        public getMultimediasResponse() {
        }
        
        public getMultimediasResponse(ServiceSemana.ServiceSemana2.getMultimediasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMultimediasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMultimediasResult;
        
        public getMultimediasResponseBody() {
        }
        
        public getMultimediasResponseBody(string getMultimediasResult) {
            this.getMultimediasResult = getMultimediasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGalerias", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getGaleriasRequestBody Body;
        
        public getGaleriasRequest() {
        }
        
        public getGaleriasRequest(ServiceSemana.ServiceSemana2.getGaleriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageSize;
        
        public getGaleriasRequestBody() {
        }
        
        public getGaleriasRequestBody(int pageNumber, int pageSize) {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getGaleriasResponseBody Body;
        
        public getGaleriasResponse() {
        }
        
        public getGaleriasResponse(ServiceSemana.ServiceSemana2.getGaleriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGaleriasResult;
        
        public getGaleriasResponseBody() {
        }
        
        public getGaleriasResponseBody(string getGaleriasResult) {
            this.getGaleriasResult = getGaleriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorocoposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorocopos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getHorocoposRequestBody Body;
        
        public getHorocoposRequest() {
        }
        
        public getHorocoposRequest(ServiceSemana.ServiceSemana2.getHorocoposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorocoposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idTipo;
        
        public getHorocoposRequestBody() {
        }
        
        public getHorocoposRequestBody(int idTipo) {
            this.idTipo = idTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorocoposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorocoposResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getHorocoposResponseBody Body;
        
        public getHorocoposResponse() {
        }
        
        public getHorocoposResponse(ServiceSemana.ServiceSemana2.getHorocoposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorocoposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHorocoposResult;
        
        public getHorocoposResponseBody() {
        }
        
        public getHorocoposResponseBody(string getHorocoposResult) {
            this.getHorocoposResult = getHorocoposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersus", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getVersusRequestBody Body;
        
        public getVersusRequest() {
        }
        
        public getVersusRequest(ServiceSemana.ServiceSemana2.getVersusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVersusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idItem;
        
        public getVersusRequestBody() {
        }
        
        public getVersusRequestBody(int idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.getVersusResponseBody Body;
        
        public getVersusResponse() {
        }
        
        public getVersusResponse(ServiceSemana.ServiceSemana2.getVersusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVersusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getVersusResult;
        
        public getVersusResponseBody() {
        }
        
        public getVersusResponseBody(string getVersusResult) {
            this.getVersusResult = getVersusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findItemsByAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findItemsByAuthor", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.findItemsByAuthorRequestBody Body;
        
        public findItemsByAuthorRequest() {
        }
        
        public findItemsByAuthorRequest(ServiceSemana.ServiceSemana2.findItemsByAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findItemsByAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idAuthor;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        public findItemsByAuthorRequestBody() {
        }
        
        public findItemsByAuthorRequestBody(int idAuthor, int pageSize, int pageNumber) {
            this.idAuthor = idAuthor;
            this.pageSize = pageSize;
            this.pageNumber = pageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findItemsByAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findItemsByAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.findItemsByAuthorResponseBody Body;
        
        public findItemsByAuthorResponse() {
        }
        
        public findItemsByAuthorResponse(ServiceSemana.ServiceSemana2.findItemsByAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findItemsByAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string findItemsByAuthorResult;
        
        public findItemsByAuthorResponseBody() {
        }
        
        public findItemsByAuthorResponseBody(string findItemsByAuthorResult) {
            this.findItemsByAuthorResult = findItemsByAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lstCrucigramasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lstCrucigramas", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.lstCrucigramasRequestBody Body;
        
        public lstCrucigramasRequest() {
        }
        
        public lstCrucigramasRequest(ServiceSemana.ServiceSemana2.lstCrucigramasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lstCrucigramasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageSize;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        public lstCrucigramasRequestBody() {
        }
        
        public lstCrucigramasRequestBody(int pageSize, int pageNumber) {
            this.pageSize = pageSize;
            this.pageNumber = pageNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class lstCrucigramasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="lstCrucigramasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServiceSemana2.lstCrucigramasResponseBody Body;
        
        public lstCrucigramasResponse() {
        }
        
        public lstCrucigramasResponse(ServiceSemana.ServiceSemana2.lstCrucigramasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class lstCrucigramasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string lstCrucigramasResult;
        
        public lstCrucigramasResponseBody() {
        }
        
        public lstCrucigramasResponseBody(string lstCrucigramasResult) {
            this.lstCrucigramasResult = lstCrucigramasResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsItemSoapChannel : ServiceSemana.ServiceSemana2.wsItemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsItemSoapClient : System.ServiceModel.ClientBase<ServiceSemana.ServiceSemana2.wsItemSoap>, ServiceSemana.ServiceSemana2.wsItemSoap {
        
        public wsItemSoapClient() {
        }
        
        public wsItemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsItemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsItemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsItemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ServiceSemana.ServiceSemana2.findItemResponse findItem(ServiceSemana.ServiceSemana2.findItemRequest request) {
            return base.Channel.findItem(request);
        }
        
        public ServiceSemana.ServiceSemana2.getItemsResponse getItems(ServiceSemana.ServiceSemana2.getItemsRequest request) {
            return base.Channel.getItems(request);
        }
        
        public ServiceSemana.ServiceSemana2.getItemsSeccionesResponse getItemsSecciones(ServiceSemana.ServiceSemana2.getItemsSeccionesRequest request) {
            return base.Channel.getItemsSecciones(request);
        }
        
        public ServiceSemana.ServiceSemana2.getItemsByEdicionResponse getItemsByEdicion(ServiceSemana.ServiceSemana2.getItemsByEdicionRequest request) {
            return base.Channel.getItemsByEdicion(request);
        }
        
        public ServiceSemana.ServiceSemana2.getItemsBySeccionResponse getItemsBySeccion(ServiceSemana.ServiceSemana2.getItemsBySeccionRequest request) {
            return base.Channel.getItemsBySeccion(request);
        }
        
        public ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionResponse getItemsByEdicionActualSeccion(ServiceSemana.ServiceSemana2.getItemsByEdicionActualSeccionRequest request) {
            return base.Channel.getItemsByEdicionActualSeccion(request);
        }
        
        public ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaResponse getItemsBySeccionRecursiva(ServiceSemana.ServiceSemana2.getItemsBySeccionRecursivaRequest request) {
            return base.Channel.getItemsBySeccionRecursiva(request);
        }
        
        public ServiceSemana.ServiceSemana2.getTerminosResponse getTerminos(ServiceSemana.ServiceSemana2.getTerminosRequest request) {
            return base.Channel.getTerminos(request);
        }
        
        public ServiceSemana.ServiceSemana2.getPreguntasResponse getPreguntas(ServiceSemana.ServiceSemana2.getPreguntasRequest request) {
            return base.Channel.getPreguntas(request);
        }
        
        public ServiceSemana.ServiceSemana2.getPreguntaResponse getPregunta(ServiceSemana.ServiceSemana2.getPreguntaRequest request) {
            return base.Channel.getPregunta(request);
        }
        
        public ServiceSemana.ServiceSemana2.addPreguntaResponse addPregunta(ServiceSemana.ServiceSemana2.addPreguntaRequest request) {
            return base.Channel.addPregunta(request);
        }
        
        public ServiceSemana.ServiceSemana2.getNextMultimediaResponse getNextMultimedia(ServiceSemana.ServiceSemana2.getNextMultimediaRequest request) {
            return base.Channel.getNextMultimedia(request);
        }
        
        public ServiceSemana.ServiceSemana2.getImageResponse getImage(ServiceSemana.ServiceSemana2.getImageRequest request) {
            return base.Channel.getImage(request);
        }
        
        public ServiceSemana.ServiceSemana2.getGaleriaResponse getGaleria(ServiceSemana.ServiceSemana2.getGaleriaRequest request) {
            return base.Channel.getGaleria(request);
        }
        
        public ServiceSemana.ServiceSemana2.getGaleryResponse getGalery(ServiceSemana.ServiceSemana2.getGaleryRequest request) {
            return base.Channel.getGalery(request);
        }
        
        public ServiceSemana.ServiceSemana2.getFotosHomeResponse getFotosHome(ServiceSemana.ServiceSemana2.getFotosHomeRequest request) {
            return base.Channel.getFotosHome(request);
        }
        
        public ServiceSemana.ServiceSemana2.addVoteResponse addVote(ServiceSemana.ServiceSemana2.addVoteRequest request) {
            return base.Channel.addVote(request);
        }
        
        public ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingResponse getMultimediasByAdvancedSearching(ServiceSemana.ServiceSemana2.getMultimediasByAdvancedSearchingRequest request) {
            return base.Channel.getMultimediasByAdvancedSearching(request);
        }
        
        public ServiceSemana.ServiceSemana2.getMultimediasResponse getMultimedias(ServiceSemana.ServiceSemana2.getMultimediasRequest request) {
            return base.Channel.getMultimedias(request);
        }
        
        public ServiceSemana.ServiceSemana2.getGaleriasResponse getGalerias(ServiceSemana.ServiceSemana2.getGaleriasRequest request) {
            return base.Channel.getGalerias(request);
        }
        
        public ServiceSemana.ServiceSemana2.getHorocoposResponse getHorocopos(ServiceSemana.ServiceSemana2.getHorocoposRequest request) {
            return base.Channel.getHorocopos(request);
        }
        
        public ServiceSemana.ServiceSemana2.getVersusResponse getVersus(ServiceSemana.ServiceSemana2.getVersusRequest request) {
            return base.Channel.getVersus(request);
        }
        
        public ServiceSemana.ServiceSemana2.findItemsByAuthorResponse findItemsByAuthor(ServiceSemana.ServiceSemana2.findItemsByAuthorRequest request) {
            return base.Channel.findItemsByAuthor(request);
        }
        
        public ServiceSemana.ServiceSemana2.lstCrucigramasResponse lstCrucigramas(ServiceSemana.ServiceSemana2.lstCrucigramasRequest request) {
            return base.Channel.lstCrucigramas(request);
        }
    }
}
