//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.17929
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceSemana.ServicesJetSet {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesJetSet.wsItemSoap")]
    public interface wsItemSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento title del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/findItem", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.findItemResponse findItem(ServiceSemana.ServicesJetSet.findItemRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento title del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItems", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getItemsResponse getItems(ServiceSemana.ServicesJetSet.getItemsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getItemsByEdicionResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsByEdicion", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getItemsByEdicionResponse getItemsByEdicion(ServiceSemana.ServicesJetSet.getItemsByEdicionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento what del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsBySeccion", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getItemsBySeccionResponse getItemsBySeccion(ServiceSemana.ServicesJetSet.getItemsBySeccionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento what del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getItemsBySeccionRecursiva", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaResponse getItemsBySeccionRecursiva(ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento title del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTerminos", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getTerminosResponse getTerminos(ServiceSemana.ServicesJetSet.getTerminosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento title del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreguntas", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getPreguntasResponse getPreguntas(ServiceSemana.ServicesJetSet.getPreguntasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getPreguntaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPregunta", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getPreguntaResponse getPregunta(ServiceSemana.ServicesJetSet.getPreguntaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento title del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addPregunta", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.addPreguntaResponse addPregunta(ServiceSemana.ServicesJetSet.addPreguntaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getNextMultimediaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNextMultimedia", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getNextMultimediaResponse getNextMultimedia(ServiceSemana.ServicesJetSet.getNextMultimediaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idsItem del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getImage", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getImageResponse getImage(ServiceSemana.ServicesJetSet.getImageRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento idItem del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGaleria", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getGaleriaResponse getGaleria(ServiceSemana.ServicesJetSet.getGaleriaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento addVoteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addVote", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.addVoteResponse addVote(ServiceSemana.ServicesJetSet.addVoteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getMultimediasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getMultimedias", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getMultimediasResponse getMultimedias(ServiceSemana.ServicesJetSet.getMultimediasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getGaleriasResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getGalerias", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getGaleriasResponse getGalerias(ServiceSemana.ServicesJetSet.getGaleriasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getHorocoposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getHorocopos", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getHorocoposResponse getHorocopos(ServiceSemana.ServicesJetSet.getHorocoposRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento getVersusResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getVersus", ReplyAction="*")]
        ServiceSemana.ServicesJetSet.getVersusResponse getVersus(ServiceSemana.ServicesJetSet.getVersusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findItemRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findItem", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.findItemRequestBody Body;
        
        public findItemRequest() {
        }
        
        public findItemRequest(ServiceSemana.ServicesJetSet.findItemRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findItemRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public findItemRequestBody() {
        }
        
        public findItemRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class findItemResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="findItemResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.findItemResponseBody Body;
        
        public findItemResponse() {
        }
        
        public findItemResponse(ServiceSemana.ServicesJetSet.findItemResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class findItemResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string findItemResult;
        
        public findItemResponseBody() {
        }
        
        public findItemResponseBody(string findItemResult) {
            this.findItemResult = findItemResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItems", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsRequestBody Body;
        
        public getItemsRequest() {
        }
        
        public getItemsRequest(ServiceSemana.ServicesJetSet.getItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sortBy;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool asc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int idTipoItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public bool calculadora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int pageSize;
        
        public getItemsRequestBody() {
        }
        
        public getItemsRequestBody(string title, string sortBy, bool asc, int idTipoItem, int idSeccion, bool calculadora, int pageNumber, int pageSize) {
            this.title = title;
            this.sortBy = sortBy;
            this.asc = asc;
            this.idTipoItem = idTipoItem;
            this.idSeccion = idSeccion;
            this.calculadora = calculadora;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsResponseBody Body;
        
        public getItemsResponse() {
        }
        
        public getItemsResponse(ServiceSemana.ServicesJetSet.getItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsResult;
        
        public getItemsResponseBody() {
        }
        
        public getItemsResponseBody(string getItemsResult) {
            this.getItemsResult = getItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsByEdicionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsByEdicion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsByEdicionRequestBody Body;
        
        public getItemsByEdicionRequest() {
        }
        
        public getItemsByEdicionRequest(ServiceSemana.ServicesJetSet.getItemsByEdicionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsByEdicionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEdicion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageSize;
        
        public getItemsByEdicionRequestBody() {
        }
        
        public getItemsByEdicionRequestBody(int idEdicion, int pageNumber, int pageSize) {
            this.idEdicion = idEdicion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsByEdicionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsByEdicionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsByEdicionResponseBody Body;
        
        public getItemsByEdicionResponse() {
        }
        
        public getItemsByEdicionResponse(ServiceSemana.ServicesJetSet.getItemsByEdicionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsByEdicionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsByEdicionResult;
        
        public getItemsByEdicionResponseBody() {
        }
        
        public getItemsByEdicionResponseBody(string getItemsByEdicionResult) {
            this.getItemsByEdicionResult = getItemsByEdicionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccion", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsBySeccionRequestBody Body;
        
        public getItemsBySeccionRequest() {
        }
        
        public getItemsBySeccionRequest(ServiceSemana.ServicesJetSet.getItemsBySeccionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string what;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        public getItemsBySeccionRequestBody() {
        }
        
        public getItemsBySeccionRequestBody(string what, int idSeccion, int pageNumber, int pageSize) {
            this.what = what;
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccionResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsBySeccionResponseBody Body;
        
        public getItemsBySeccionResponse() {
        }
        
        public getItemsBySeccionResponse(ServiceSemana.ServicesJetSet.getItemsBySeccionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsBySeccionResult;
        
        public getItemsBySeccionResponseBody() {
        }
        
        public getItemsBySeccionResponseBody(string getItemsBySeccionResult) {
            this.getItemsBySeccionResult = getItemsBySeccionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionRecursivaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccionRecursiva", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequestBody Body;
        
        public getItemsBySeccionRecursivaRequest() {
        }
        
        public getItemsBySeccionRecursivaRequest(ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionRecursivaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string what;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        public getItemsBySeccionRecursivaRequestBody() {
        }
        
        public getItemsBySeccionRecursivaRequestBody(string what, int idSeccion, int pageNumber, int pageSize) {
            this.what = what;
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemsBySeccionRecursivaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getItemsBySeccionRecursivaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaResponseBody Body;
        
        public getItemsBySeccionRecursivaResponse() {
        }
        
        public getItemsBySeccionRecursivaResponse(ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getItemsBySeccionRecursivaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getItemsBySeccionRecursivaResult;
        
        public getItemsBySeccionRecursivaResponseBody() {
        }
        
        public getItemsBySeccionRecursivaResponseBody(string getItemsBySeccionRecursivaResult) {
            this.getItemsBySeccionRecursivaResult = getItemsBySeccionRecursivaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTerminosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTerminos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getTerminosRequestBody Body;
        
        public getTerminosRequest() {
        }
        
        public getTerminosRequest(ServiceSemana.ServicesJetSet.getTerminosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTerminosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageSize;
        
        public getTerminosRequestBody() {
        }
        
        public getTerminosRequestBody(string title, int pageNumber, int pageSize) {
            this.title = title;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTerminosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTerminosResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getTerminosResponseBody Body;
        
        public getTerminosResponse() {
        }
        
        public getTerminosResponse(ServiceSemana.ServicesJetSet.getTerminosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTerminosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getTerminosResult;
        
        public getTerminosResponseBody() {
        }
        
        public getTerminosResponseBody(string getTerminosResult) {
            this.getTerminosResult = getTerminosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreguntas", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getPreguntasRequestBody Body;
        
        public getPreguntasRequest() {
        }
        
        public getPreguntasRequest(ServiceSemana.ServicesJetSet.getPreguntasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int pageSize;
        
        public getPreguntasRequestBody() {
        }
        
        public getPreguntasRequestBody(string title, int idSeccion, int pageNumber, int pageSize) {
            this.title = title;
            this.idSeccion = idSeccion;
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreguntasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getPreguntasResponseBody Body;
        
        public getPreguntasResponse() {
        }
        
        public getPreguntasResponse(ServiceSemana.ServicesJetSet.getPreguntasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPreguntasResult;
        
        public getPreguntasResponseBody() {
        }
        
        public getPreguntasResponseBody(string getPreguntasResult) {
            this.getPreguntasResult = getPreguntasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPregunta", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getPreguntaRequestBody Body;
        
        public getPreguntaRequest() {
        }
        
        public getPreguntaRequest(ServiceSemana.ServicesJetSet.getPreguntaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idItem;
        
        public getPreguntaRequestBody() {
        }
        
        public getPreguntaRequestBody(int idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreguntaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreguntaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getPreguntaResponseBody Body;
        
        public getPreguntaResponse() {
        }
        
        public getPreguntaResponse(ServiceSemana.ServicesJetSet.getPreguntaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreguntaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getPreguntaResult;
        
        public getPreguntaResponseBody() {
        }
        
        public getPreguntaResponseBody(string getPreguntaResult) {
            this.getPreguntaResult = getPreguntaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPreguntaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPregunta", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.addPreguntaRequestBody Body;
        
        public addPreguntaRequest() {
        }
        
        public addPreguntaRequest(ServiceSemana.ServicesJetSet.addPreguntaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPreguntaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idSeccion;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string autor;
        
        public addPreguntaRequestBody() {
        }
        
        public addPreguntaRequestBody(string title, int idSeccion, string autor) {
            this.title = title;
            this.idSeccion = idSeccion;
            this.autor = autor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addPreguntaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addPreguntaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.addPreguntaResponseBody Body;
        
        public addPreguntaResponse() {
        }
        
        public addPreguntaResponse(ServiceSemana.ServicesJetSet.addPreguntaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addPreguntaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addPreguntaResult;
        
        public addPreguntaResponseBody() {
        }
        
        public addPreguntaResponseBody(string addPreguntaResult) {
            this.addPreguntaResult = addPreguntaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextMultimediaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextMultimedia", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getNextMultimediaRequestBody Body;
        
        public getNextMultimediaRequest() {
        }
        
        public getNextMultimediaRequest(ServiceSemana.ServicesJetSet.getNextMultimediaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextMultimediaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idItem;
        
        public getNextMultimediaRequestBody() {
        }
        
        public getNextMultimediaRequestBody(int idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextMultimediaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextMultimediaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getNextMultimediaResponseBody Body;
        
        public getNextMultimediaResponse() {
        }
        
        public getNextMultimediaResponse(ServiceSemana.ServicesJetSet.getNextMultimediaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextMultimediaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getNextMultimediaResult;
        
        public getNextMultimediaResponseBody() {
        }
        
        public getNextMultimediaResponseBody(string getNextMultimediaResult) {
            this.getNextMultimediaResult = getNextMultimediaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getImage", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getImageRequestBody Body;
        
        public getImageRequest() {
        }
        
        public getImageRequest(ServiceSemana.ServicesJetSet.getImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idsItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idTipoImagen;
        
        public getImageRequestBody() {
        }
        
        public getImageRequestBody(string idsItem, int idTipoImagen) {
            this.idsItem = idsItem;
            this.idTipoImagen = idTipoImagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getImageResponseBody Body;
        
        public getImageResponse() {
        }
        
        public getImageResponse(ServiceSemana.ServicesJetSet.getImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getImageResult;
        
        public getImageResponseBody() {
        }
        
        public getImageResponseBody(string getImageResult) {
            this.getImageResult = getImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleria", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getGaleriaRequestBody Body;
        
        public getGaleriaRequest() {
        }
        
        public getGaleriaRequest(ServiceSemana.ServicesJetSet.getGaleriaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string idItem;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string idTipoImagen;
        
        public getGaleriaRequestBody() {
        }
        
        public getGaleriaRequestBody(string idItem, string idTipoImagen) {
            this.idItem = idItem;
            this.idTipoImagen = idTipoImagen;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleriaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getGaleriaResponseBody Body;
        
        public getGaleriaResponse() {
        }
        
        public getGaleriaResponse(ServiceSemana.ServicesJetSet.getGaleriaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGaleriaResult;
        
        public getGaleriaResponseBody() {
        }
        
        public getGaleriaResponseBody(string getGaleriaResult) {
            this.getGaleriaResult = getGaleriaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addVoteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addVote", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.addVoteRequestBody Body;
        
        public addVoteRequest() {
        }
        
        public addVoteRequest(ServiceSemana.ServicesJetSet.addVoteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addVoteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idEncuesta;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idRespuesta;
        
        public addVoteRequestBody() {
        }
        
        public addVoteRequestBody(int idEncuesta, int idRespuesta) {
            this.idEncuesta = idEncuesta;
            this.idRespuesta = idRespuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addVoteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addVoteResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.addVoteResponseBody Body;
        
        public addVoteResponse() {
        }
        
        public addVoteResponse(ServiceSemana.ServicesJetSet.addVoteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addVoteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addVoteResult;
        
        public addVoteResponseBody() {
        }
        
        public addVoteResponseBody(string addVoteResult) {
            this.addVoteResult = addVoteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMultimediasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMultimedias", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getMultimediasRequestBody Body;
        
        public getMultimediasRequest() {
        }
        
        public getMultimediasRequest(ServiceSemana.ServicesJetSet.getMultimediasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMultimediasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageSize;
        
        public getMultimediasRequestBody() {
        }
        
        public getMultimediasRequestBody(int pageNumber, int pageSize) {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getMultimediasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getMultimediasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getMultimediasResponseBody Body;
        
        public getMultimediasResponse() {
        }
        
        public getMultimediasResponse(ServiceSemana.ServicesJetSet.getMultimediasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getMultimediasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getMultimediasResult;
        
        public getMultimediasResponseBody() {
        }
        
        public getMultimediasResponseBody(string getMultimediasResult) {
            this.getMultimediasResult = getMultimediasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGalerias", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getGaleriasRequestBody Body;
        
        public getGaleriasRequest() {
        }
        
        public getGaleriasRequest(ServiceSemana.ServicesJetSet.getGaleriasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriasRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int pageNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int pageSize;
        
        public getGaleriasRequestBody() {
        }
        
        public getGaleriasRequestBody(int pageNumber, int pageSize) {
            this.pageNumber = pageNumber;
            this.pageSize = pageSize;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getGaleriasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getGaleriasResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getGaleriasResponseBody Body;
        
        public getGaleriasResponse() {
        }
        
        public getGaleriasResponse(ServiceSemana.ServicesJetSet.getGaleriasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getGaleriasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getGaleriasResult;
        
        public getGaleriasResponseBody() {
        }
        
        public getGaleriasResponseBody(string getGaleriasResult) {
            this.getGaleriasResult = getGaleriasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorocoposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorocopos", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getHorocoposRequestBody Body;
        
        public getHorocoposRequest() {
        }
        
        public getHorocoposRequest(ServiceSemana.ServicesJetSet.getHorocoposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorocoposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idTipo;
        
        public getHorocoposRequestBody() {
        }
        
        public getHorocoposRequestBody(int idTipo) {
            this.idTipo = idTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getHorocoposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getHorocoposResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getHorocoposResponseBody Body;
        
        public getHorocoposResponse() {
        }
        
        public getHorocoposResponse(ServiceSemana.ServicesJetSet.getHorocoposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getHorocoposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getHorocoposResult;
        
        public getHorocoposResponseBody() {
        }
        
        public getHorocoposResponseBody(string getHorocoposResult) {
            this.getHorocoposResult = getHorocoposResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersus", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getVersusRequestBody Body;
        
        public getVersusRequest() {
        }
        
        public getVersusRequest(ServiceSemana.ServicesJetSet.getVersusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVersusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idItem;
        
        public getVersusRequestBody() {
        }
        
        public getVersusRequestBody(int idItem) {
            this.idItem = idItem;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVersusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getVersusResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceSemana.ServicesJetSet.getVersusResponseBody Body;
        
        public getVersusResponse() {
        }
        
        public getVersusResponse(ServiceSemana.ServicesJetSet.getVersusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getVersusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getVersusResult;
        
        public getVersusResponseBody() {
        }
        
        public getVersusResponseBody(string getVersusResult) {
            this.getVersusResult = getVersusResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsItemSoapChannel : ServiceSemana.ServicesJetSet.wsItemSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsItemSoapClient : System.ServiceModel.ClientBase<ServiceSemana.ServicesJetSet.wsItemSoap>, ServiceSemana.ServicesJetSet.wsItemSoap {
        
        public wsItemSoapClient() {
        }
        
        public wsItemSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsItemSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsItemSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsItemSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.findItemResponse ServiceSemana.ServicesJetSet.wsItemSoap.findItem(ServiceSemana.ServicesJetSet.findItemRequest request) {
            return base.Channel.findItem(request);
        }
        
        public string findItem(string title) {
            ServiceSemana.ServicesJetSet.findItemRequest inValue = new ServiceSemana.ServicesJetSet.findItemRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.findItemRequestBody();
            inValue.Body.title = title;
            ServiceSemana.ServicesJetSet.findItemResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).findItem(inValue);
            return retVal.Body.findItemResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getItemsResponse ServiceSemana.ServicesJetSet.wsItemSoap.getItems(ServiceSemana.ServicesJetSet.getItemsRequest request) {
            return base.Channel.getItems(request);
        }
        
        public string getItems(string title, string sortBy, bool asc, int idTipoItem, int idSeccion, bool calculadora, int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getItemsRequest inValue = new ServiceSemana.ServicesJetSet.getItemsRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getItemsRequestBody();
            inValue.Body.title = title;
            inValue.Body.sortBy = sortBy;
            inValue.Body.asc = asc;
            inValue.Body.idTipoItem = idTipoItem;
            inValue.Body.idSeccion = idSeccion;
            inValue.Body.calculadora = calculadora;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getItemsResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getItems(inValue);
            return retVal.Body.getItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getItemsByEdicionResponse ServiceSemana.ServicesJetSet.wsItemSoap.getItemsByEdicion(ServiceSemana.ServicesJetSet.getItemsByEdicionRequest request) {
            return base.Channel.getItemsByEdicion(request);
        }
        
        public string getItemsByEdicion(int idEdicion, int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getItemsByEdicionRequest inValue = new ServiceSemana.ServicesJetSet.getItemsByEdicionRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getItemsByEdicionRequestBody();
            inValue.Body.idEdicion = idEdicion;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getItemsByEdicionResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getItemsByEdicion(inValue);
            return retVal.Body.getItemsByEdicionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getItemsBySeccionResponse ServiceSemana.ServicesJetSet.wsItemSoap.getItemsBySeccion(ServiceSemana.ServicesJetSet.getItemsBySeccionRequest request) {
            return base.Channel.getItemsBySeccion(request);
        }
        
        public string getItemsBySeccion(string what, int idSeccion, int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getItemsBySeccionRequest inValue = new ServiceSemana.ServicesJetSet.getItemsBySeccionRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getItemsBySeccionRequestBody();
            inValue.Body.what = what;
            inValue.Body.idSeccion = idSeccion;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getItemsBySeccionResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getItemsBySeccion(inValue);
            return retVal.Body.getItemsBySeccionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaResponse ServiceSemana.ServicesJetSet.wsItemSoap.getItemsBySeccionRecursiva(ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequest request) {
            return base.Channel.getItemsBySeccionRecursiva(request);
        }
        
        public string getItemsBySeccionRecursiva(string what, int idSeccion, int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequest inValue = new ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaRequestBody();
            inValue.Body.what = what;
            inValue.Body.idSeccion = idSeccion;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getItemsBySeccionRecursivaResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getItemsBySeccionRecursiva(inValue);
            return retVal.Body.getItemsBySeccionRecursivaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getTerminosResponse ServiceSemana.ServicesJetSet.wsItemSoap.getTerminos(ServiceSemana.ServicesJetSet.getTerminosRequest request) {
            return base.Channel.getTerminos(request);
        }
        
        public string getTerminos(string title, int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getTerminosRequest inValue = new ServiceSemana.ServicesJetSet.getTerminosRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getTerminosRequestBody();
            inValue.Body.title = title;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getTerminosResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getTerminos(inValue);
            return retVal.Body.getTerminosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getPreguntasResponse ServiceSemana.ServicesJetSet.wsItemSoap.getPreguntas(ServiceSemana.ServicesJetSet.getPreguntasRequest request) {
            return base.Channel.getPreguntas(request);
        }
        
        public string getPreguntas(string title, int idSeccion, int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getPreguntasRequest inValue = new ServiceSemana.ServicesJetSet.getPreguntasRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getPreguntasRequestBody();
            inValue.Body.title = title;
            inValue.Body.idSeccion = idSeccion;
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getPreguntasResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getPreguntas(inValue);
            return retVal.Body.getPreguntasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getPreguntaResponse ServiceSemana.ServicesJetSet.wsItemSoap.getPregunta(ServiceSemana.ServicesJetSet.getPreguntaRequest request) {
            return base.Channel.getPregunta(request);
        }
        
        public string getPregunta(int idItem) {
            ServiceSemana.ServicesJetSet.getPreguntaRequest inValue = new ServiceSemana.ServicesJetSet.getPreguntaRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getPreguntaRequestBody();
            inValue.Body.idItem = idItem;
            ServiceSemana.ServicesJetSet.getPreguntaResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getPregunta(inValue);
            return retVal.Body.getPreguntaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.addPreguntaResponse ServiceSemana.ServicesJetSet.wsItemSoap.addPregunta(ServiceSemana.ServicesJetSet.addPreguntaRequest request) {
            return base.Channel.addPregunta(request);
        }
        
        public string addPregunta(string title, int idSeccion, string autor) {
            ServiceSemana.ServicesJetSet.addPreguntaRequest inValue = new ServiceSemana.ServicesJetSet.addPreguntaRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.addPreguntaRequestBody();
            inValue.Body.title = title;
            inValue.Body.idSeccion = idSeccion;
            inValue.Body.autor = autor;
            ServiceSemana.ServicesJetSet.addPreguntaResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).addPregunta(inValue);
            return retVal.Body.addPreguntaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getNextMultimediaResponse ServiceSemana.ServicesJetSet.wsItemSoap.getNextMultimedia(ServiceSemana.ServicesJetSet.getNextMultimediaRequest request) {
            return base.Channel.getNextMultimedia(request);
        }
        
        public string getNextMultimedia(int idItem) {
            ServiceSemana.ServicesJetSet.getNextMultimediaRequest inValue = new ServiceSemana.ServicesJetSet.getNextMultimediaRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getNextMultimediaRequestBody();
            inValue.Body.idItem = idItem;
            ServiceSemana.ServicesJetSet.getNextMultimediaResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getNextMultimedia(inValue);
            return retVal.Body.getNextMultimediaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getImageResponse ServiceSemana.ServicesJetSet.wsItemSoap.getImage(ServiceSemana.ServicesJetSet.getImageRequest request) {
            return base.Channel.getImage(request);
        }
        
        public string getImage(string idsItem, int idTipoImagen) {
            ServiceSemana.ServicesJetSet.getImageRequest inValue = new ServiceSemana.ServicesJetSet.getImageRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getImageRequestBody();
            inValue.Body.idsItem = idsItem;
            inValue.Body.idTipoImagen = idTipoImagen;
            ServiceSemana.ServicesJetSet.getImageResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getImage(inValue);
            return retVal.Body.getImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getGaleriaResponse ServiceSemana.ServicesJetSet.wsItemSoap.getGaleria(ServiceSemana.ServicesJetSet.getGaleriaRequest request) {
            return base.Channel.getGaleria(request);
        }
        
        public string getGaleria(string idItem, string idTipoImagen) {
            ServiceSemana.ServicesJetSet.getGaleriaRequest inValue = new ServiceSemana.ServicesJetSet.getGaleriaRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getGaleriaRequestBody();
            inValue.Body.idItem = idItem;
            inValue.Body.idTipoImagen = idTipoImagen;
            ServiceSemana.ServicesJetSet.getGaleriaResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getGaleria(inValue);
            return retVal.Body.getGaleriaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.addVoteResponse ServiceSemana.ServicesJetSet.wsItemSoap.addVote(ServiceSemana.ServicesJetSet.addVoteRequest request) {
            return base.Channel.addVote(request);
        }
        
        public string addVote(int idEncuesta, int idRespuesta) {
            ServiceSemana.ServicesJetSet.addVoteRequest inValue = new ServiceSemana.ServicesJetSet.addVoteRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.addVoteRequestBody();
            inValue.Body.idEncuesta = idEncuesta;
            inValue.Body.idRespuesta = idRespuesta;
            ServiceSemana.ServicesJetSet.addVoteResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).addVote(inValue);
            return retVal.Body.addVoteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getMultimediasResponse ServiceSemana.ServicesJetSet.wsItemSoap.getMultimedias(ServiceSemana.ServicesJetSet.getMultimediasRequest request) {
            return base.Channel.getMultimedias(request);
        }
        
        public string getMultimedias(int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getMultimediasRequest inValue = new ServiceSemana.ServicesJetSet.getMultimediasRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getMultimediasRequestBody();
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getMultimediasResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getMultimedias(inValue);
            return retVal.Body.getMultimediasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getGaleriasResponse ServiceSemana.ServicesJetSet.wsItemSoap.getGalerias(ServiceSemana.ServicesJetSet.getGaleriasRequest request) {
            return base.Channel.getGalerias(request);
        }
        
        public string getGalerias(int pageNumber, int pageSize) {
            ServiceSemana.ServicesJetSet.getGaleriasRequest inValue = new ServiceSemana.ServicesJetSet.getGaleriasRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getGaleriasRequestBody();
            inValue.Body.pageNumber = pageNumber;
            inValue.Body.pageSize = pageSize;
            ServiceSemana.ServicesJetSet.getGaleriasResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getGalerias(inValue);
            return retVal.Body.getGaleriasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getHorocoposResponse ServiceSemana.ServicesJetSet.wsItemSoap.getHorocopos(ServiceSemana.ServicesJetSet.getHorocoposRequest request) {
            return base.Channel.getHorocopos(request);
        }
        
        public string getHorocopos(int idTipo) {
            ServiceSemana.ServicesJetSet.getHorocoposRequest inValue = new ServiceSemana.ServicesJetSet.getHorocoposRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getHorocoposRequestBody();
            inValue.Body.idTipo = idTipo;
            ServiceSemana.ServicesJetSet.getHorocoposResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getHorocopos(inValue);
            return retVal.Body.getHorocoposResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceSemana.ServicesJetSet.getVersusResponse ServiceSemana.ServicesJetSet.wsItemSoap.getVersus(ServiceSemana.ServicesJetSet.getVersusRequest request) {
            return base.Channel.getVersus(request);
        }
        
        public string getVersus(int idItem) {
            ServiceSemana.ServicesJetSet.getVersusRequest inValue = new ServiceSemana.ServicesJetSet.getVersusRequest();
            inValue.Body = new ServiceSemana.ServicesJetSet.getVersusRequestBody();
            inValue.Body.idItem = idItem;
            ServiceSemana.ServicesJetSet.getVersusResponse retVal = ((ServiceSemana.ServicesJetSet.wsItemSoap)(this)).getVersus(inValue);
            return retVal.Body.getVersusResult;
        }
    }
}
